Repository Hey-Doctor/HeyDoctor_Backend, pull requests merged in 2025-07, with the labels that each got.

#4 [feat] 공용 DB 생성 및 테스트
  .idea/gradle.xml
  .idea/uiDesigner.xml
  HELP.md
  build.gradle
  src/main/java/HeyDoctor/HeyDoctor_Backend/api/controller/MemberController.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/api/dto/MemberRequestDto.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/member/repository/MemberRepository.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/member/service/MemberService.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/member/service/MemberServiceImpl.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/controller/UserController.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/dto/UserRequest.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/dto/UserResponse.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/model/User.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/repository/UserRepository.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/service/UserService.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/service/UserServiceImpl.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/global/config/AppConfig.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/global/exception/CustomException.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/global/exception/ErrorCode.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/global/exception/GlobalExceptionHandler.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/global/security/DummySecurityConfig.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/util/TimeUtil.java
  src/main/resources/application.properties
  src/test/java/HeyDoctor/HeyDoctor_Backend/HeyDoctorBackendApplicationTests.java
  src/test/java/HeyDoctor/HeyDoctor_Backend/domain/users/model/SignUpTest.java
Labels: feat, refactor, test, chore, remove

#5 [Feat] 로그인, 회원가입 구현
  build.gradle
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/SignupApplication.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/controller/UserController.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/dto/CommonResponse.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/dto/LoginRequest.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/dto/LoginResponse.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/dto/UserRegisterRequest.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/entity/User.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/repository/UserRepository.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/domain/service/UserService.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/global/config/WebConfig.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/User/global/util/JwtUtil.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/controller/UserController.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/dto/UserRequest.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/dto/UserResponse.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/model/User.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/repository/UserRepository.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/service/UserService.java
  src/main/java/HeyDoctor/HeyDoctor_Backend/domain/users/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/HeyDoctor/HeyDoctor_Backend/domain/users/model/SignUpTest.java
  src/test/java/HeyDoctor/HeyDoctor_Backend/domain/users/model/signup/SignupApplicationTests.java
  src/test/java/HeyDoctor/HeyDoctor_Backend/domain/users/model/signup/service/UserServiceTest.java
Labels: feat, chore, remove

#10 [docs] 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
Labels: docs, 천수

#11 [docs] PR 템플릿 생성
  .github/pull_request_template.md
Labels: docs, 천수
